from dataloaders import RenderedDataLoader
import pytorch_lightning as pl
from torch.utils.data import DataLoader
import models
from pytorch_lightning.callbacks import ModelCheckpoint, StochasticWeightAveraging
import inference
import warnings
from pytorch_lightning import loggers as pl_loggers


def unified_training(class_key,
                    chm_mean,
                    chm_std,
                    lr,
                    height_threshold,
                    class_weights,
                    trained_backbone,
                    features_dict,
                    num_intermediate_classes,
                    pre_train_folder,
                    train_folder,
                    valid_folder,
                    test_folder,
                    pre_training_epochs,
                    refine_epochs,
                    pre_train_batch_size,
                    refine_batch_size,
                    pre_train_workers,
                    refine_workers,
                    log_dir):

    pl.seed_everything(42)
    extra_labels = ""
    for key, value in features_dict.items():
        extra_labels = extra_labels + f"{key}_{value}_"

    refine_callback = ModelCheckpoint(
        dirpath='ckpts/unified_training', 
        filename=f'niwo_refine_{extra_labels}'+'{ova:.2f}_{epoch}',
        #every_n_epochs=log_every,
        monitor='ova',
        save_on_train_epoch_end=True,
        mode='max',
        save_top_k = 3
        )

    pre_train_callback = ModelCheckpoint(
        dirpath='ckpts/unified_training', 
        filename=f'niwo_pre_train_{extra_labels}'+'{epoch}',
        every_n_epochs=pre_training_epochs,
        save_on_train_epoch_end=True,
        save_top_k = -1
        )
    
    pre_train_ckpt = f'ckpts/unified_training/niwo_pre_train_{extra_labels}epoch={pre_training_epochs-1}.ckpt'

    pre_model = models.SwaVModelUnified(class_key,
                                    chm_mean,
                                    chm_std,
                                    lr,
                                    height_threshold,
                                    class_weights,
                                    trained_backbone,
                                    features_dict,
                                    num_intermediate_classes,
                                    pre_training=True)

    pre_train_data = RenderedDataLoader(pre_train_folder)
    pre_train_loader = DataLoader(pre_train_data, batch_size=pre_train_batch_size, num_workers=pre_train_workers, pin_memory=True)

    train_dataset = RenderedDataLoader(train_folder)
    train_loader = DataLoader(train_dataset, batch_size=refine_batch_size, num_workers=refine_workers)

    valid_dataset = RenderedDataLoader(valid_folder)
    valid_loader = DataLoader(valid_dataset, batch_size=1, num_workers=refine_workers)

    test_dataset = RenderedDataLoader(test_folder)
    test_loader = DataLoader(test_dataset, batch_size=1, num_workers=refine_workers)

    tb_logger = pl_loggers.TensorBoardLogger(save_dir=log_dir)

    pre_trainer = pl.Trainer(accelerator="gpu", max_epochs=pre_training_epochs, callbacks=[pre_train_callback], logger=tb_logger)
    
    pre_trainer.fit(pre_model, pre_train_loader)

    refiner = pl.Trainer(accelerator="gpu", max_epochs=refine_epochs, callbacks=[refine_callback], logger=tb_logger)

    refine_model = models.SwaVModelUnified.load_from_checkpoint(pre_train_ckpt, pre_training=False)
    refiner.fit(refine_model, train_dataloaders=train_loader, val_dataloaders=valid_loader)
    refiner.test(ckpt_path='best', dataloaders=test_loader)
    

if __name__ == "__main__":

    #TODO:
    #HPARAM TUNING
    #TRY WITHOUT CHM FILTER
    #TRY FEWER INPUTS
    #TRY ADDITIONAL AUGMENTATION FOR REFINE TRAINING

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10,
#                         'chm': 1,
#                         'azm': 1, 
#                         'shadow': 1, 
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10,
#                         'chm': 1,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10,
#                         'azm': 1,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10,
#                         'shadow': 1,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10,
#                         'chm': 1,
#                         'azm': 1
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10,
#                         'chm': 1,
#                         'shadow': 1
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10,
#                         'azm': 1,
#                         'shadow': 1
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')
# ####### ICA
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'ica' : 10,
#                         'chm': 1,
#                         'azm': 1,
#                         'shadow': 1, 
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'ica' : 10
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'ica' : 10,
#                         'chm': 1,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'ica' : 10,
#                         'azm': 1,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'ica' : 10,
#                         'shadow': 1,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'ica' : 10,
#                         'chm': 1,
#                         'azm': 1
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')
                    
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'ica' : 10,
#                         'chm': 1,
#                         'shadow': 1
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'ica' : 10,
#                         'azm': 1,
#                         'shadow': 1
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

# ######  RAW                
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'raw_bands' : 15,
#                         'chm': 1,
#                         'azm': 1,
#                         'shadow': 1,  
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'raw_bands' : 15
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'raw_bands' : 15,
#                         'chm': 1,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'raw_bands' : 15,
#                         'azm': 1,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'raw_bands' : 15,
#                         'shadow': 1,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'raw_bands' : 15,
#                         'chm': 1,
#                         'azm': 1
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')
                    
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'raw_bands' : 15,
#                         'chm': 1,
#                         'shadow': 1
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'raw_bands' : 15,
#                         'azm': 1,
#                         'shadow': 1
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

# ####### MIXED
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10,
#                         'ica': 10,
#                         'raw_bands' : 15,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10,
#                         'raw_bands' : 15,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'ica': 10,
#                         'raw_bands' : 15,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')

#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca': 10,
#                         'ica': 10,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')
    unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
                    chm_mean=4.015508459469479,
                    chm_std=4.809300736115787,
                    lr=5e-4,
                    height_threshold=5,
                    class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
                    trained_backbone=True,
                    features_dict={
                        'pca' : 3,
                        'ica': 3,
                        'raw_bands' : 15,
                    },
                    num_intermediate_classes = 256,
                    pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
                    train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
                    valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
                    test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
                    pre_training_epochs = 250,
                    refine_epochs = 800,
                    pre_train_batch_size = 2048,
                    refine_batch_size = 32,
                    pre_train_workers = 8,
                    refine_workers = 1,
                    log_dir='exp_logs/')
    unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
                chm_mean=4.015508459469479,
                chm_std=4.809300736115787,
                lr=5e-4,
                height_threshold=5,
                class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
                trained_backbone=True,
                features_dict={
                    'pca' : 3,
                    'ica': 3,
                    'raw_bands' : 15,
                    'shadow': 1
                },
                num_intermediate_classes = 256,
                pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
                train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
                valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
                test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
                pre_training_epochs = 250,
                refine_epochs = 800,
                pre_train_batch_size = 2048,
                refine_batch_size = 32,
                pre_train_workers = 8,
                refine_workers = 1,
                log_dir='exp_logs/')
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 3,
#                         'ica': 3,
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'ica': 3,
#                         'raw_bands': 15
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca': 3,
#                         'raw_bands': 15
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 10,
#                         'ica': 10,
#                         'raw_bands' : 15,
#                         'chm': 1,
#                         'azm': 1,
#                         'shadow': 1,  
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')
#     unified_training(class_key={0: 'PIEN', 1: 'ABLAL', 2: 'PICOL', 3: 'PIFL2'},
#                     chm_mean=4.015508459469479,
#                     chm_std=4.809300736115787,
#                     lr=5e-4,
#                     height_threshold=5,
#                     class_weights=[0.6434426229508197, 0.7405660377358491, 1.353448275862069, 2.8035714285714284],
#                     trained_backbone=True,
#                     features_dict={
#                         'pca' : 3,
#                         'ica': 3,
#                         'raw_bands' : 15,
#                         'chm': 1,
#                         'azm': 1,
#                         'shadow': 1,  
#                     },
#                     num_intermediate_classes = 256,
#                     pre_train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/raw_training/',
#                     train_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_training',
#                     valid_folder = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_valid',
#                     test_folder  = 'C:/Users/tonyt/Documents/Research/datasets/tensors/niwo_2020_pca_ica_shadow_extra_all/label_test',
#                     pre_training_epochs = 15,
#                     refine_epochs = 200,
#                     pre_train_batch_size = 2048,
#                     refine_batch_size = 32,
#                     pre_train_workers = 8,
#                     refine_workers = 1,
#                     log_dir='exp_logs/')